# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClusterName', models.CharField(max_length=30)),
                ('TaskDefinitionName', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=30)),
                ('ContainerName', models.CharField(max_length=30)),
                ('PublicIp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FgTempInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clustername', models.CharField(max_length=30)),
                ('TaskDefinitionName', models.CharField(max_length=30)),
                ('ServiceName', models.CharField(max_length=30)),
                ('ContainerName', models.CharField(max_length=30)),
                ('PublicIp', models.CharField(max_length=30)),
            ],
        ),
    ]
