#!/bin/bash
rm -r /root/.helm/

export KUBECONFIG=$KUBECONFIG:~/.kube/config
#sudo -u ubuntu bash <<EOF
./get_helm.sh
sleep 30

kubectl apply -f kube-prometheus-grafana/helm-rbac.yaml
sleep 60
helm init --service-account helm
sleep 30


helm install --name kube-prometheus kube-prometheus-grafana/helm/prometheus -f kube-prometheus-grafana/values.yaml --namespace monitoring
sleep 30
helm install --name kube-grafana kube-prometheus-grafana/helm/grafana -f kube-prometheus-grafana/values.yaml --namespace monitoring
sleep 30
rm azgrafana.txt
kubectl get svc grafana -n monitoring \
    -o jsonpath="{.status.loadBalancer.ingress[*].ip}" > /home/ubuntu/venv/mmp/aws/azgrafana.txt
#EOF
