# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('first_name', models.CharField(max_length=40)),
            ],
        ),
    ]
