# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AksClusterName', models.CharField(max_length=30)),
                ('ResourceGroupName', models.CharField(max_length=30)),
                ('WorkerNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AksTempInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AksClusterName', models.CharField(max_length=30)),
                ('ResourceGroupName', models.CharField(max_length=30)),
                ('WorkerNo', models.CharField(max_length=30)),
            ],
        ),
    ]
