# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aksinfo',
            name='ExternalIP',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
        migrations.AddField(
            model_name='aksinfo',
            name='MonitoringIP',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
    ]
