# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustername', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('MasterASG', models.CharField(max_length=30)),
                ('SlaveASG', models.CharField(max_length=30)),
                ('MasterNo', models.IntegerField()),
                ('SlaveNo', models.IntegerField()),
                ('Provtime', models.CharField(max_length=50)),
            ],
        ),
    ]
