# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrasetup', '0002_auto_20180604_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='clusterdetails_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustername', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=40)),
                ('masterno', models.PositiveIntegerField()),
                ('instatypem', models.CharField(max_length=30)),
                ('slaveno', models.PositiveIntegerField()),
                ('instatypes', models.CharField(max_length=30)),
                ('masterasg', models.CharField(max_length=40)),
                ('slaveasg', models.CharField(max_length=40)),
            ],
        ),
    ]
