# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GkeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GkeClusterName', models.CharField(max_length=30)),
                ('ProjectId', models.CharField(max_length=40)),
                ('Zone', models.CharField(max_length=30)),
                ('Nodes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GkeTempInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GkeClusterName', models.CharField(max_length=30)),
                ('ProjectId', models.CharField(max_length=30)),
                ('Nodes', models.CharField(max_length=30)),
                ('DiskSize', models.CharField(max_length=30)),
            ],
        ),
    ]
