# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-03 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterStack', models.CharField(max_length=30)),
                ('EksClusterName', models.CharField(max_length=30)),
                ('WorkersStack', models.CharField(max_length=30)),
                ('WorkerNo', models.PositiveIntegerField()),
            ],
        ),
    ]
