# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EksTempInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterStack', models.CharField(max_length=30)),
                ('EksClusterName', models.CharField(max_length=30)),
                ('WorkersStack', models.CharField(max_length=30)),
                ('WorkerNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='eksinfo',
            name='WorkerNo',
            field=models.CharField(max_length=30),
        ),
    ]
