# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eks', '0002_auto_20180718_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksinfo',
            name='ExternalIP',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
        migrations.AlterField(
            model_name='eksinfo',
            name='EksClusterName',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='eksinfo',
            name='MasterStack',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='eksinfo',
            name='WorkerNo',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='eksinfo',
            name='WorkersStack',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='ekstempinfo',
            name='EksClusterName',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='ekstempinfo',
            name='MasterStack',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='ekstempinfo',
            name='WorkerNo',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='ekstempinfo',
            name='WorkersStack',
            field=models.CharField(max_length=230),
        ),
    ]
