# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eks', '0003_auto_20190225_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksinfo',
            name='MonitoringIP',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
    ]
